### ISSUE TITLE
Unable to compare diff

### ISSUE THREAD

**Issue by NickJamesBTC** [jaydorsey/env_compare#46]
I can list each app separately but am unable to compare them why am I running into auth issues

```
ec list app1
=== app1 Config Vars
FOO:   bar
```

```
ec diff --all app1 app2
Traceback (most recent call last):
        22: from /Users/nick/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'
        21: from /Users/nick/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'
        20: from /Users/nick/.rvm/gems/ruby-2.6.6/bin/ec:23:in `<main>'
        19: from /Users/nick/.rvm/gems/ruby-2.6.6/bin/ec:23:in `load'
        18: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/env_compare-0.1.4/exe/ec:6:in `<top (required)>'
        17: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        16: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        15: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        14: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        13: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/env_compare-0.1.4/lib/env_compare/cli.rb:32:in `diff'
        12: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/env_compare-0.1.4/lib/env_compare/cli.rb:75:in `heroku_results'
        11: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/env_compare-0.1.4/lib/env_compare/cli.rb:75:in `each_with_object'
        10: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/env_compare-0.1.4/lib/env_compare/cli.rb:75:in `each'
         9: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/env_compare-0.1.4/lib/env_compare/cli.rb:78:in `block in heroku_results'
         8: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/env_compare-0.1.4/lib/env_compare/cli.rb:104:in `config_vars_for_app'
         7: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/platform-api-2.2.0/lib/platform-api/client.rb:1503:in `info_for_app'
         6: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/heroics-0.0.25/lib/heroics/resource.rb:28:in `method_missing'
         5: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/heroics-0.0.25/lib/heroics/link.rb:66:in `run'
         4: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/heroics-0.0.25/lib/heroics/link.rb:111:in `request_with_cache'
         3: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/excon-0.73.0/lib/excon/connection.rb:279:in `request'
         2: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/excon-0.73.0/lib/excon/connection.rb:448:in `response'
         1: from /Users/nick/.rvm/gems/ruby-2.6.6/gems/excon-0.73.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
/Users/nick/.rvm/gems/ruby-2.6.6/gems/excon-0.73.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected([200, 201, 202, 204, 206, 304]) <=> Actual(401 Unauthorized) (Excon::Error::Unauthorized)
```

**Comment by NickJamesBTC** [comment]
I had a local env file cache superseding my dev app..
